# Generated by Django 4.0.3 on 2024-03-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holding1',
        ),
    ]
